#! /bin/python
import os,sys,time

def clear():
	try:
		os.system('clear')
	except:
		os.system('cls')
	else:
		pass
	return

def port(file='NULL'):
	if file == 'NULL':
		print('file not found')
		exit()
	else:
		with open(file,'r+') as r:
			global lyric
			lyric=r.readlines()
	#print(lyric)
	#time.sleep(10)
	return lyric

def lyrics(s):
	os.system('clear')
	for words in s:
		for word in words:
			if word == ' ':
				os.system('clear')
			else:
				print(word,end='',sep=' ',flush=True).center(30)
				time.sleep(0.25)	

# """import something that will stream the audio to get the timing?"""


def main():
	print('make sure to input a file\n rt-lyrics file')
	time.sleep(2)
	port(sys.argv[1])
	lyrics(lyric)

if __name__=="__main__":
	main()

