#! /bin/python
import os,sys,time

def port(file='NULL'):
	if file == 'NULL':
		print('file not found')
		exit()
	else:
		with open(file,'r+') as r:
			global lyric
			lyric=r.readlines()
	return lyric

def lyrics(s):
	os.system('clear')
	for words in s:
		for word in words:
			cur_word=[]
			cur_word.append(word)
	
			if word == ' ':
				os.system('clear')
				print(cur_word)
				cur_word.clear()
			else:
				print(word,end='',sep=' ',flush=True)
				time.sleep(0.15)	
def main():
	print('make sure to input a file\n rt-lyrics file')
	time.sleep(2)
	port(sys.argv[1])
	lyrics(lyric)

if __name__=="__main__":
	main()

